### ISSUE TITLE
Mac: Error: No native build was found for platform=darwin arch=arm64 runtime=node

### ISSUE THREAD

**Issue by kuncle** [BennyTheDev/pipe-wallet#3]
run: node pipe.mjs walletcreate xxx
Error: No native build was found for platform=darwin arch=arm64 runtime=node abi=108 uv=1 armv=8 libc=glibc node=18.16.0

**Comment by BennyTheDev** [comment]
that's probably bip32 related, I will check that on macos

**Comment by kuncle** [comment]
any update?

**Comment by ghost** [comment]
I use macOS 14.1
Node v18.17.1
wallet works fine.
Have you updated the dependencies?
My package.ison, try comparing to yours, maybe an update from the repository is required. There was a wallet update a couple days ago.
```
{
  "dependencies": {
    "@cmdcode/tapscript": "1.2.7",
    "bip32": "3.0.1",
    "bip39": "^3.1.0",
    "config": "^3.3.9",
    "cuid": "^3.0.0",
    "graceful-goodbye": "^1.3.0",
    "level": "^8.0.0",
    "level-sublevel": "^6.6.5",
    "os": "^0.1.2",
    "tiny-secp256k1": "^2.2.3"
  }
}
```

**Comment by kuncle** [comment]
> I use macOS 14.1 Node v18.17.1 wallet works fine. Have you updated the dependencies? My package.ison, try comparing to yours, maybe an update from the repository is required. There was a wallet update a couple days ago.
> 
> ```
> {
>   "dependencies": {
>     "@cmdcode/tapscript": "1.2.7",
>     "bip32": "3.0.1",
>     "bip39": "^3.1.0",
>     "config": "^3.3.9",
>     "cuid": "^3.0.0",
>     "graceful-goodbye": "^1.3.0",
>     "level": "^8.0.0",
>     "level-sublevel": "^6.6.5",
>     "os": "^0.1.2",
>     "tiny-secp256k1": "^2.2.3"
>   }
> }
> ```

sorry for the delayed reply, but it still doesn't work.

**Comment by kuncle** [comment]
emmm, just use npm install classic-level --build-from-source command solved it.

"""
If you don't want to use the prebuilt binary for the platform you are installing on, specify the --build-from-source flag when you install. One of:
npm install classic-level --build-from-source
""" from https://github.com/Level/classic-level
