### ISSUE TITLE
Decentralisation

### ISSUE THREAD

**Issue by OxMarco** [BennyTheDev/pipe-wallet#4]
Can the transactions and wallet generation be created and signed locally and broadcasted to the node at a later stage?

**Comment by ghost** [comment]
Now you can rem sendrawtransaction and change output log "result"  txid : sign_result,
```
//let broadcast_result = await exe(btc_cli_path + ' sendrawtransaction "'+sign_result.hex+'" ' + max_fee);
        //broadcast_result = broadcast_result.trim();

        const result = {
            error : false,
            txid : sign_result,
            amount : amount.toString()
        };
```

**Comment by OxMarco** [comment]
I don't think the problem is in the broadcasting, it's rather in the wallet creation and the fact that a name collision can essentially allow a bad actor to "steal" another user funds

**Comment by ghost** [comment]
sorry for the misunderstanding, I thought you were interested in how to verify a transaction before sending it.
As for the node, you mean if someone uses rpcallowip=*?

**Comment by OxMarco** [comment]
I mean like creating the wallet on the local machine and then using pipe to submit the transaction without exposing the private key itself. Imagine people not having a local bitcoin node and needing to use QuickNode or a similar solution.

**Comment by turinglabsorg** [comment]
Probably we just need to understand how we can ask xverse or similar wallets (using satsconnect) give us a fresh new wallet, like a change wallet for example. In this case we can avoid pipe website generate privkeys and exposing them to the public

**Comment by OxMarco** [comment]
Simply avoiding to call `fundrawtransaction` and adding the `--disable-private-keys` flag during wallet creation should do the trick, then users have to sign and broadcast the transaction locally. What do you think? @BennyTheDev
