### ISSUE TITLE
Imported address balance incorrect

### ISSUE THREAD

**Issue by sslisen** [BennyTheDev/pipe-wallet#6]
I have imported an address by seed phrase which hold PIPE balance for sure.
But the pipe-wallet shown 0 balance.
I sure that the seed phrase is correct.
It's weird that if i import the address into another wallet such as sparrow or unisat. at least I can see the balance of sats.
But in pipe-wallet nodeJS, it is 0 balance.
I don't know what is wrong with this issue?

![image](https://github.com/BennyTheDev/pipe-wallet/assets/59131974/854b5128-91fb-43ce-bd4c-6c648aa983c2)
![image](https://github.com/BennyTheDev/pipe-wallet/assets/59131974/f4a26689-f65f-4360-a3df-7cdadb503bc8)

**Comment by sslisen** [comment]
I use getaddressinfo command in bitcoin core console. 
"ismine": false.

**Comment by sslisen** [comment]
> I have imported an address by seed phrase which hold PIPE balance for sure. But the pipe-wallet shown 0 balance. I sure that the seed phrase is correct. It's weird that if i import the address into another wallet such as sparrow or unisat. at least I can see the balance of sats. But in pipe-wallet nodeJS, it is 0 balance. I don't know what is wrong with this issue?
> 
> ![image](https://user-images.githubusercontent.com/59131974/275504381-854b5128-91fb-43ce-bd4c-6c648aa983c2.png) ![image](https://user-images.githubusercontent.com/59131974/275504510-f4a26689-f65f-4360-a3df-7cdadb503bc8.png)

![image](https://github.com/BennyTheDev/pipe-wallet/assets/59131974/c87c6cb9-e2e9-4f3b-b533-7fb126e10f91)
I have 1 utxo in this address( it is $PIPE for sue, checked on dune and other indexing web)

**Comment by ghost** [comment]
Try` bitcoin-cli -rpcwallet=<walletname> rescanblockchain 809607`

**Comment by sslisen** [comment]
> Try` bitcoin-cli -rpcwallet=<walletname> rescanblockchain 809607`

yes, I have tired. I even rescan start from 0. but it is remain the same. 0 balance 0 UTXO.

**Comment by BennyTheDev** [comment]
Check your unspents please using listunspent w/ bitcoin-cli.
The pipe-wallet filters utxos if they are not spendable.

<img width="227" alt="image" src="https://github.com/BennyTheDev/pipe-wallet/assets/1433403/d31b857b-36a3-44f4-acbf-069e1e17c350">

**Comment by sslisen** [comment]
![image](https://github.com/BennyTheDev/pipe-wallet/assets/59131974/b5069688-38a4-46d7-86ff-66ad7682d55d)
nothing here
I think maybe pipe-wallet have bug

**Comment by ghost** [comment]
Try downloading the wallet version again, install the dependencies, specify the path to the bitcoin cli. Restore this wallet under a different name. And at the end, make bitcoin-cli -rpcwallet=<walletname> rescanblockchain 809607
With the new name that you used when restoring.
Everything should work out.

**Comment by sslisen** [comment]
> Try downloading the wallet version again, install the dependencies, specify the path to the bitcoin cli. Restore this wallet under a different name. And at the end, make bitcoin-cli -rpcwallet= rescanblockchain 809607 With the new name that you used when restoring. Everything should work out.

Finally got it fixed. It turned out that I was using an old version. After following your instructions and upgrading to the latest version, everything is working fine now.
Thank you very much.

**Comment by sslisen** [comment]
@NeroZyF Thank you very much for your help.

**Comment by sslisen** [comment]
@NeroZyF I would like to consualt you another thing.
I use `node pipe.mjs sendsats <walletname> <address> <amount> <feerate>` to sent 1000 $PIPE to another address. but the input looks cripy. so many input here. I think it use my TOKEN as gas?

this is hash.
https://mempool.space/tx/7c0f8294ceb40ba495c985d2f4d50a0be16da49da01248e061963b919f5e0f71
![image](https://github.com/BennyTheDev/pipe-wallet/assets/59131974/a88a95b0-a582-43e3-8344-e423fba723cf)

**Comment by sslisen** [comment]
> @NeroZyF I would like to consualt you another thing. I use `node pipe.mjs sendsats <walletname> <address> <amount> <feerate>` to sent 1000 $PIPE to another address. but the input looks cripy. so many input here. I think it use my TOKEN as gas?
> 
> this is hash. https://mempool.space/tx/7c0f8294ceb40ba495c985d2f4d50a0be16da49da01248e061963b919f5e0f71 ![image](https://user-images.githubusercontent.com/59131974/275829808-a88a95b0-a582-43e3-8344-e423fba723cf.png)

Too much GAS used. I have normal BTC in wallet. And I don't know why the input like these.

**Comment by ghost** [comment]
I hope it's your test wallet and there's nothing super valuable in there. Because it looks like this transaction actually used your previous 546 sats inputs as a fee to the miners.
So, to transfer $PIPE you should not use `sendsats` but `sendtokens`.
You need to refill this address with some sats so that the wallet can use these sats for the fee.
```
Send tokens to a receiver from <walletname>:
node pipe.mjs sendtokens <walletname> <address> <ticker> <ID> <amount> <feerate>
```
If you have something important on your wallet, I recommend disabling the automatic sending of the transaction to the network.
You need to find lines 1552-1553 and comment them out so that they are not executed.
Next you need to change line 1557 to  `txid : sign_result,`
This way you will receive the raw transaction message inside the quotes. You can load this raw into sparrow or electrum and see what inputs and outputs the transaction will have. Since the transaction is already signed, you can send it after viewing it.
Here is how the modified code of lines 1552-1559 looks like.
```
//let broadcast_result = await exe(btc_cli_path + ' sendrawtransaction "'+sign_result.hex+'" ' + max_fee);
        //broadcast_result = broadcast_result.trim();

        const result = {
            error : false,
            txid : sign_result,
            amount : amount.toString()
        };
```
I forgot to add, please don't show the raw transaction text in discussions, I don't know for sure if it's possible to get private information out of it, but to be on the safe side I don't think you should show it.

**Comment by sslisen** [comment]
OOOH!
It's my fualt that didn't check carefully.
Great thank you for your useful info.
Let me study it for a while.

**Comment by sslisen** [comment]
> I hope it's your test wallet and there's nothing super valuable in there. Because it looks like this transaction actually used your previous 546 sats inputs as a fee to the miners. So, to transfer $PIPE you should not use `sendsats` but `sendtokens`. You need to refill this address with some sats so that the wallet can use these sats for the fee.
> 
> ```
> Send tokens to a receiver from <walletname>:
> node pipe.mjs sendtokens <walletname> <address> <ticker> <ID> <amount> <feerate>
> ```
> 
> If you have something important on your wallet, I recommend disabling the automatic sending of the transaction to the network. You need to find lines 1552-1553 and comment them out so that they are not executed. Next you need to change line 1557 to `txid : sign_result,` This way you will receive the raw transaction message inside the quotes. You can load this raw into sparrow or electrum and see what inputs and outputs the transaction will have. Since the transaction is already signed, you can send it after viewing it. Here is how the modified code of lines 1552-1559 looks like.
> 
> ```
> //let broadcast_result = await exe(btc_cli_path + ' sendrawtransaction "'+sign_result.hex+'" ' + max_fee);
>         //broadcast_result = broadcast_result.trim();
> 
>         const result = {
>             error : false,
>             txid : sign_result,
>             amount : amount.toString()
>         };
> ```
> 
> I forgot to add, please don't show the raw transaction text in discussions, I don't know for sure if it's possible to get private information out of it, but to be on the safe side I don't think you should show it.

Now I understand!!
Great great thanks to you.!!

**Comment by sslisen** [comment]
Should I change line 1552 broadcast_result.trim() to sign_result.trim() ?

**Comment by sslisen** [comment]
> Should I change line 1552 broadcast_result.trim() to sign_result.trim() ?

I understand how to do.
